services:
  minio:
    image: minio/minio:latest
    container_name: aquawatch_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - aquawatch_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: aquawatch_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aquawatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aquawatch_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: aquawatch_mqtt
    ports:
      - "1883:1883"
      - "9002:9002"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - aquawatch_net

  st-model:
    build: ./st-model
    container_name: aquawatch_stmodel
    environment:
      PG_HOST: aquawatch_db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: aquawatch
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - aquawatch_net
      
  mqtt-gateway:
    build: ./mqtt-gateway
    container_name: aquawatch_gateway
    depends_on:
      - mosquitto
      - timescaledb
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - PG_HOST=aquawatch_db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=aquawatch
      - DATA_SOURCE=csv
    networks:
      - aquawatch_net

  satellite-service:
    build: ./satellite-service
    container_name: aquawatch_satellite
    depends_on:
      - minio
    env_file:
      - ./satellite-service/.env
    networks:
      - aquawatch_net

  alert-service:
    build: ./alert-service
    container_name: aquawatch_alert
    depends_on:
      - mosquitto
      - timescaledb
    env_file:
      - ./alert-service/.env
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - PG_HOST=aquawatch_db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=aquawatch
    networks:
      - aquawatch_net


networks:
  aquawatch_net:
    driver: bridge

volumes:
  minio_data:
  postgres_data:
  mosquitto_data:
  mosquitto_config:
