# SonarQube Project Configuration
sonar.projectKey=AquaWatch
sonar.projectName=AquaWatch
sonar.projectVersion=1.0

# Connection properties (Can be overridden by CLI)
sonar.host.url=http://localhost:9005
sonar.login=sqp_3d36f79ad01983f8d06371d78fa93eb563b995fa

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/tests/**,**/.venv/**,**/sql/**,**/*.txt,**/*.log
sonar.test.inclusions=**/tests/**

# Coverage paths
mqtt-gateway.sonar.javascript.lcov.reportPaths=mqtt-gateway/coverage/lcov.info

# Project structure
sonar.modules=mqtt-gateway,alert-service,satellite-service,st-model,frontend

mqtt-gateway.sonar.projectBaseDir=mqtt-gateway
mqtt-gateway.sonar.sources=src

alert-service.sonar.projectBaseDir=alert-service
alert-service.sonar.sources=src

satellite-service.sonar.projectBaseDir=satellite-service
satellite-service.sonar.sources=src

st-model.sonar.projectBaseDir=st-model
st-model.sonar.sources=.
st-model.sonar.exclusions=venv/**,**/__pycache__/**

frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
